### ISSUE TITLE
errors

### ISSUE THREAD

**Issue by buebasek** [coats1337/Discordapp-TokenGrabber#14]
hi , i add you on discord. Can you accept invite?
i wonna explain my problem

**Comment by coats1337** [comment]
tell me the errors here

**Comment by ES-Nighty** [comment]
Hey @coats1337 please does exist a video for explain how to use ? Thanks for yout **help.******

**Comment by coats1337** [comment]
> Hey @coats1337 please does exist a video for explain how to use ? Thanks for yout **help.******

currently not tbh

**Comment by coats1337** [comment]
Readme.MD, it's been decided ill leave this discontinued while i work on a new version.
