### ISSUE TITLE
It Crashes when someone open it

### ISSUE THREAD

**Issue by NiNj4HAXYT** [coats1337/Discordapp-TokenGrabber#5]
**It Crashes when someone open it, i don't get any tokens on that webhook, can you explain the Process?**

**Comment by coats1337** [comment]
did you even try to meet the program requirements before actually obfuscating it?

**Comment by NiNj4HAXYT** [comment]
Where are the requirements? you didn't provied a requirements.txt

**Comment by NiNj4HAXYT** [comment]
What is your discord can i talk with you pls

**Comment by NiNj4HAXYT** [comment]
please tell me your your discord name, it's very important

**Comment by coats1337** [comment]
shut the fuck up and coats.#1337
holy fuck

**Comment by NiNj4HAXYT** [comment]
Yes
