### ISSUE TITLE
Error in Chrome Password Decryption

### ISSUE THREAD

**Issue by NiNj4HAXYT** [coats1337/Discordapp-TokenGrabber#6]
**

> File "grab.py", line 220, in <module>
>     Grabber().start()
>   File "grab.py", line 188, in start
>     self.grabPassword()
>   File "grab.py", line 128, in grabPassword
>     password = win32crypt.CryptUnprotectData(result[2])[1].decode()
> pywintypes.error: (87, 'CryptProtectData', 'The parameter is incorrect.')

**

**Comment by coats1337** [comment]
we're aware, read the README. thanks.
